#!/bin/bash
#
# Root utility script for Anura translation management.
# Refined for d3msudo fork and Linux Mint stability.

function generate_po()
{
    echo "Anura: Synchronizing and generating translation files..."
    
    # Navigate to po directory safely
    cd po || { echo "Error: 'po' directory not found"; return 1; }

    # CAUTION: Ensure your Weblate remote is correctly configured for the new repository.
    # git pull https://hosted.weblate.org/git/anura/anura/default

    # Initialize a clean POT file
    echo "" > anura.pot

    # Define all source files for translation extraction
    # Using the updated namespace: com.github.d3msudo.anura
    SOURCES=(
        "../data/com.github.d3msudo.anura.gschema.xml"
        "../data/*.in"
        "../data/ui/*.blp"
        "../anura/*.py"
        "../anura/services/*.py"
        "../anura/types/*.py"
        "../anura/widgets/*.py"
    )

    # Extract strings using xgettext
    # -L Python is used for .blp files as a reliable extraction method
    xgettext --add-comments \
             --keyword=_ \
             --keyword=C_:1c,2 \
             --from-code=UTF-8 \
             --package-name="anura" \
             --output=anura.pot \
             ${SOURCES[@]}

    # Rebuild the LINGUAS file and merge PO files
    echo "# This file is autogenerated by generate_po()" > LINGUAS
    
    for po in *.po; do
        [ -f "$po" ] || continue # Skip if no .po files exist
        
        echo "Merging: $po"
        # Create a safe temporary file for the merge
        TEMP_PO=$(mktemp)
        msgmerge --no-fuzzy-matching -N "$po" anura.pot > "$TEMP_PO"
        mv "$TEMP_PO" "$po"
        
        # Extract language code and update LINGUAS
        language=${po%.po}
        echo "$language" >> LINGUAS
    done

    cd ..
    echo "Anura: PO generation and LINGUAS update complete."
}

# Execute function
generate_po