# This file is part of Anura.
# Copyright (C) 2026 D3M-Sudo (Anura)
#
# SPDX-License-Identifier: MIT

"""Integrity verification for runtime-downloaded Tesseract models (NEW-F1).

Anura downloads extra language models at runtime. Pinning the upstream URL to a
release tag keeps the location stable, but a tag is a *mutable* pointer: a
rewritten tag (or a TLS-terminating intermediary) could serve a tampered model
to Tesseract, which parses untrusted binary input.

To close that gap the expected identity of every model published by the pinned
tags is committed to the repository in
``anura/data/tessdata_checksums.json`` — generated by
``build-aux/generate_tessdata_checksums.py`` — and verified while the model is
being streamed, before it is installed.

The manifest is checked against ``anura/config.py`` at release time by
``build-aux/check_tessdata_consistency.py``, so a re-pinned URL cannot silently
ship with a stale manifest.
"""

from functools import lru_cache
import hashlib
import json
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from loguru import logger

from anura.models.tessdata_checksum import TessdataChecksum

#: Integrity manifest shipped alongside the application code.
CHECKSUMS_PATH = Path(__file__).resolve().parent.parent / "data" / "tessdata_checksums.json"

_GITHUB_URL_PREFIX = "https://github.com/"


def _parse_base_url(base_url: str) -> tuple[str, str, str] | None:
    """Return ``(owner, repo, ref)`` for a GitHub raw base URL, or ``None``."""
    if not base_url.startswith(_GITHUB_URL_PREFIX):
        return None

    # Expected path shape: /<owner>/<repo>/raw/<ref>/
    parts = [segment for segment in urlparse(base_url).path.split("/") if segment]
    if len(parts) != 4 or parts[2] != "raw":
        return None

    owner, repo, _, ref = parts
    return owner, repo, ref


def repo_key_from_url(base_url: str) -> str | None:
    """Return the upstream repository name (e.g. ``tessdata_fast``)."""
    parsed = _parse_base_url(base_url)
    return parsed[1] if parsed else None


def ref_from_url(base_url: str) -> str | None:
    """Return the pinned upstream git ref (e.g. ``4.1.0``)."""
    parsed = _parse_base_url(base_url)
    return parsed[2] if parsed else None


def tree_api_url(base_url: str) -> str | None:
    """Return the GitHub tree API URL listing the pinned ref of the repository."""
    parsed = _parse_base_url(base_url)
    if parsed is None:
        return None

    owner, repo, ref = parsed
    return f"https://api.github.com/repos/{owner}/{repo}/git/trees/{ref}?recursive=1"


@lru_cache(maxsize=1)
def load_checksums() -> dict[str, Any]:
    """Load the integrity manifest, indexed by repository name.

    Returns:
        Mapping of ``repository name -> {"tag": str, "url": str, "files": {...}}``.
        An empty mapping is returned when the manifest is missing or malformed,
        which makes every verification fail closed.
    """
    try:
        manifest = json.loads(CHECKSUMS_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        logger.error(f"Anura: Cannot read tessdata checksums manifest '{CHECKSUMS_PATH}': {e}")
        return {}

    repositories = manifest.get("repositories") if isinstance(manifest, dict) else None
    return repositories if isinstance(repositories, dict) else {}


def get_expected_checksum(base_url: str, filename: str) -> TessdataChecksum | None:
    """Return the pinned identity of ``filename`` in the repo behind ``base_url``.

    Fails closed (returns ``None``) when the manifest is unavailable, when the
    manifest does not cover ``filename``, or when the manifest is stale because
    the configured URL points at a different upstream ref.

    Args:
        base_url: Pinned tessdata base URL from ``anura.config``.
        filename: Model file name (e.g. ``eng.traineddata``).
    """
    repo = repo_key_from_url(base_url)
    if repo is None:
        logger.error(f"Anura: Malformed tessdata base URL: '{base_url}'")
        return None

    repository = load_checksums().get(repo)
    if not isinstance(repository, dict):
        logger.error(f"Anura: No pinned checksums for repository '{repo}'.")
        return None

    expected_ref = ref_from_url(base_url)
    manifest_ref = repository.get("tag")
    if manifest_ref != expected_ref:
        logger.error(
            f"Anura: Checksums manifest for '{repo}' is pinned to '{manifest_ref}' but the configured "
            f"URL points to '{expected_ref}'. Regenerate anura/data/tessdata_checksums.json with "
            "build-aux/generate_tessdata_checksums.py."
        )
        return None

    files = repository.get("files")
    if not isinstance(files, dict):
        logger.error(f"Anura: Malformed checksums manifest for repository '{repo}'.")
        return None

    entry = files.get(filename)
    if not isinstance(entry, dict):
        logger.error(f"Anura: No pinned checksum for '{repo}/{filename}'.")
        return None

    try:
        return TessdataChecksum.from_dict(filename, entry)
    except (KeyError, TypeError, ValueError) as e:
        logger.error(f"Anura: Invalid checksum entry for '{repo}/{filename}': {e}")
        return None


class GitBlobHasher:
    """Incremental SHA-1 over the *git blob* representation of a download.

    Git object ids are content-addressed: ``sha1("blob <size>\\0" + content)``
    reproduces the hash published by the GitHub tree API for the pinned ref.
    Hashing incrementally while the response is streamed means the model never
    needs a second pass on disk.
    """

    __slots__ = ("_declared_size", "_hash", "_received")

    def __init__(self, declared_size: int) -> None:
        if declared_size < 0:
            raise ValueError("declared_size must not be negative")

        self._declared_size = declared_size
        self._received = 0
        # usedforsecurity=False: this is content addressing, not a signature.
        # SHA-1 mirrors git's own object identity, which is strong enough to
        # pin a blob an attacker would have to match byte for byte.
        self._hash = hashlib.sha1(usedforsecurity=False)
        self._hash.update(f"blob {declared_size}\x00".encode())

    def update(self, chunk: bytes) -> None:
        """Feed one chunk of the streamed model."""
        self._hash.update(chunk)
        self._received += len(chunk)

    @property
    def received(self) -> int:
        """Number of bytes hashed so far."""
        return self._received

    @property
    def declared_size(self) -> int:
        """Size the integrity manifest expects for this model."""
        return self._declared_size

    def matches(self, expected: TessdataChecksum) -> bool:
        """Return ``True`` when length and git blob digest match ``expected``."""
        return self._received == expected.size and self._hash.hexdigest() == expected.sha1
