name: Flatpak Release & Package

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  flatpak-builder:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Anura Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: com.github.d3msudo.anura.flatpak
          manifest-path: flatpak/com.github.d3msudo.anura.json
          cache: true
          run-tests: false

      - name: Upload Flatpak Bundle to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: com.github.d3msudo.anura.flatpak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
