name: Flatpak Build Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  flatpak-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Anura Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: com.github.d3msudo.anura.flatpak
          manifest-path: flatpak/com.github.d3msudo.anura.json
          cache: true
          
          repository-name: flathub
          repository-url: https://dl.flathub.org/repo/flathub.flatpakrepo
