name: CI Quality Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Ruff Linter
        uses: chartboost/ruff-action@v1
        with:
          args: check --select E,F,W,I --target-version py312 --fix --unsafe-fixes
